### ISSUE TITLE
Route front-end pages

### ISSUE THREAD

**Issue by fancyaction** [chingu-voyages/v29-bears-team-05#41]
**__Feature Description__**
User can click links and see basic html on home page, cheatsheet list page, and user profile page.

**__Major User Stories/tasks__**
- [ ] Link and component for Home Page
- [ ] Link and component for Cheetsheet List Page
- [ ] Link and component for User Profile Page
